language: node_js
node_js:
  - "12"
before_install:
  - yarn upgrade ---latest
  - npm install
  - yarn install

cache:
  yarn: true

install:
  - yarn

matrix:
  include:
    - name: build
      script:
        - yarn build

    - name: build_core
      script:
        - yarn build:core

skip_build:
  README.md