language: node_js
node_js:
  - "10"
before_install:
  - yarn upgrade ---latest

cache:
  yarn: true

install:
  - yarn

matrix:
  include:
    - name: build
      script:
        - yarn --version
        - yarn build

    - name: build_core
      script:
        - yarn build:core


    - name: build_popup
      script:
        - yarn build:popup

    - name: lint
      script:
        - yarn lint

skip_build:
  README.md